package com.octoooo.saydo

// Generated from scripts/pairing-url-corpus.json. Do not edit.

internal data class PairingCorpusCase(
    val id: String,
    val accept: Boolean,
    val prefix: String,
    val hostParts: List<String>,
    val hostSep: String,
    val bracketHost: Boolean,
    val port: String,
    val pathQuery: String,
    val suffix: String,
    val token: String?,
    val expectPort: String?,
) {
    fun input(): String {
        val host = hostParts.joinToString(hostSep)
        val authority = if (bracketHost) "[$host]" else host
        return prefix + authority + ":" + port + pathQuery + suffix
    }

    fun expectedName(): String? {
        val portOut = expectPort ?: return null
        return hostParts.joinToString(hostSep) + ":" + portOut.toInt().toString()
    }
}

internal object PairingUrlCorpus {
    val cases: List<PairingCorpusCase> = listOf(
        PairingCorpusCase(
            "accept-ipv4",
            true,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "",
            "abc",
            "47100",
        ),
        PairingCorpusCase(
            "accept-ascii-trim",
            true,
            "\n\t http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            " \r\n",
            "abc",
            "47100",
        ),
        PairingCorpusCase(
            "accept-trim-cr",
            true,
            "\rhttp://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "\r",
            "abc",
            "47100",
        ),
        PairingCorpusCase(
            "accept-trim-lf",
            true,
            "\nhttp://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "\n",
            "abc",
            "47100",
        ),
        PairingCorpusCase(
            "accept-trim-crlf",
            true,
            "\r\nhttp://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "\r\n",
            "abc",
            "47100",
        ),
        PairingCorpusCase(
            "accept-trim-mixed",
            true,
            "\r\n\t http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            " \t\r\n",
            "abc",
            "47100",
        ),
        PairingCorpusCase(
            "accept-leading-zero-port",
            true,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "047100",
            "/?token=abc",
            "",
            "abc",
            "47100",
        ),
        PairingCorpusCase(
            "accept-ula",
            true,
            "http://",
            listOf("fd12", "3456", "789a", "1", "", "1"),
            ":",
            true,
            "47100",
            "/?token=abc",
            "",
            "abc",
            "47100",
        ),
        PairingCorpusCase(
            "accept-percent-reserved",
            true,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=a%2Fb%20c%2Bd",
            "",
            "a/b c+d",
            "47100",
        ),
        PairingCorpusCase(
            "accept-percent-bmp",
            true,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=%E4%BD%A0%E5%A5%BD",
            "",
            "\u4F60\u597D",
            "47100",
        ),
        PairingCorpusCase(
            "accept-percent-non-bmp",
            true,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=%F0%90%80%80",
            "",
            "\uD800\uDC00",
            "47100",
        ),
        PairingCorpusCase(
            "reject-bom",
            false,
            "\uFEFFhttp://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-nbsp",
            false,
            "\u00A0http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-raw-space",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc def",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-raw-tab",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc\tdef",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-raw-nul",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc\u0000",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-raw-at",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc@x",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-raw-brackets",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc[x]",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-raw-non-bmp",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc\uD800\uDC00",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-bad-percent-zz",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=%zz",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-truncated-percent",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=%2",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-overlong",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=%C0%AF",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-surrogate-utf8",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=%ED%A0%80",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-truncated-utf8",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=%E4%BD",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-empty-fragment",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc#",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-userinfo",
            false,
            "http://user@",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-duplicate-token",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=one&token=two",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-fullwidth-digit-authority",
            false,
            "http://",
            listOf("\uFF11\uFF19\uFF12", "\uFF11\uFF16\uFF18", "\uFF11", "\uFF18"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-fullwidth-dot-authority",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            "\uFF0E",
            false,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-ideographic-dot-authority",
            false,
            "http://",
            listOf("192", "168", "1", "8"),
            "\u3002",
            false,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-circled-digit-authority",
            false,
            "http://",
            listOf("\u2460\u2468\u2461", "\u2460\u2465\u2467", "\u2460", "\u2467"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-zwsp-authority",
            false,
            "http://",
            listOf("192", "\u200B168", "1", "8"),
            ".",
            false,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "accept-ula-compressed-short",
            true,
            "http://",
            listOf("fd12", "", "1"),
            ":",
            true,
            "47100",
            "/?token=abc",
            "",
            "abc",
            "47100",
        ),
        PairingCorpusCase(
            "reject-ula-trailing-single-colon",
            false,
            "http://",
            listOf("fd12", "", "1", ""),
            ":",
            true,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-ula-leading-single-colon",
            false,
            "http://",
            listOf("", "fd12", "", "1"),
            ":",
            true,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        ),
        PairingCorpusCase(
            "reject-ula-triple-colon",
            false,
            "http://",
            listOf("fd12", "", "", "1"),
            ":",
            true,
            "47100",
            "/?token=abc",
            "",
            null,
            null,
        )
    )
}
