export { hostKind, homeDir, pathDelimiter, type HostKind } from "./host.js";
export {
  classifyKillProbe,
  isOwnErrno,
  isObjectLike,
  isProxyValue,
  readOwnData,
  readOwnErrnoCode,
  PROCESS_KILL_UNKNOWN,
  PROCESS_PROBE_UNKNOWN,
  type KillProbeKind
} from "./errno.js";
export {
  assertOwnedByCurrentUser,
  assertRealDirectory,
  fsIdentity,
  isReparsePoint,
  fsyncFile,
  fsyncDir,
  fsyncOpenFlagForHost,
  setFsyncSyncImplForTests,
  restrictOwnerOnly,
  setRestrictOwnerOnlyForTests,
  type FsIdentity,
  type FsyncKind,
  type FsyncDirResult,
  type RestrictOwnerOnly
} from "./fs.js";
export {
  agentOwnerIdentity,
  appendReapAudit,
  assignPidToJob,
  assignProcessHandleToJob,
  closeNamedJob,
  closeRawHandle,
  commandTokenForGeneration,
  closeWin32Permit,
  createSuspendedOwnedWindowsProcess,
  createWin32PermitPipe,
  roundtripWin32NamedPipe,
  commitOwnerReap,
  createNamedJob,
  effectiveKillHostKind,
  ERROR_ALREADY_EXISTS,
  exitCodeFromHandle,
  formatSayDoJobName,
  grantWin32Permit,
  HOME_OWNER_LOCK_ABORTED,
  HOME_OWNER_LOCK_FAILED,
  HOME_OWNER_LOCK_TIMEOUT,
  isKillOwnedTreeError,
  isSayDoGeneration,
  isSayDoIdentityToken,
  isSayDoJobName,
  isTrustedCommandToken,
  isTrustedOwnerBinary,
  killOwnedTree,
  namedJobActiveProcessCount,
  namedJobActiveProcessCountByName,
  namedJobContainsPid,
  observeVerifiedOwnedJob,
  observedProcessAlive,
  observedProcessAnchor,
  observedProcessBirth,
  ownerIdentityEqual,
  parseAgentOwnerRecord,
  parseAnyRuntimeOwnerRecord,
  parsePendingRuntimeOwnerRecord,
  parseRuntimeOwnerRecord,
  parseWin32CommandLine,
  quoteWin32Arg,
  quoteWin32CommandLine,
  runtimeOwnerIdentity,
  sayDoJobDigest,
  withHomeOwnerBoundary,
  withHomeOwnerBoundarySync,
  writeDurableJson,
  commitOwnerReapIfIdentity,
  isOwnerIdentityCasError,
  isProcessInJobFromHandles,
  processAlive,
  processAnchor,
  processBirth,
  processBirthFromHandle,
  processHandleCount,
  isWin32HandleOpen,
  isWin32FdClosed,
  lastWin32SpawnRollbackAudit,
  type Win32SpawnResourceAudit,
  processStillActiveFromHandle,
  brandTrustedFailure,
  projectUntrustedFailureText,
  readOwnedProcessBirth,
  sayDoJobNameMatchesIdentity,
  setKillOwnedTreeTestHooks,
  setWin32SpawnTestFault,
  SpawnRollbackRetainedError,
  win32StartupLayout,
  WIN32_PROC_THREAD_ATTRIBUTE_HANDLE_LIST,
  terminateNamedJobHandle,
  terminateProcessFromHandle,
  tryLockFileExclusive,
  waitProcessHandle,
  WIN32_ARGV_QUOTE_CASES,
  withVerifiedOwnedJob,
  win32JobIdentityOk,
  type KillClaim,
  type KillOwnedTreeTestHooks,
  type NamedJob,
  type OwnedWindowsProcess,
  type OwnedJobNativeSeam,
  type OwnerImmutableIdentity,
  type ParsedAgentOwner,
  type ParsedPendingRuntimeOwner,
  type ParsedRuntimeOwner,
  type ProcessAnchor,
  type VerifiedOwnedJobObservation,
  type VerifiedOwnedJobSession
} from "./process.js";
export { acquireExclusiveLink } from "./lock.js";
export {
  GATE_HMAC_HEADER,
  gateBindPath,
  gateDir,
  gateSecretPath,
  hmacHeaderOk,
  hmacHex,
  listenGateHttp,
  newGateSecret,
  posixGateSockPath,
  writeGateBindAndSecret,
  type GateBind,
  type GateHttpHandler,
  type GateHttpListen
} from "./gate.js";
export { openExternal } from "./open.js";
export {
  bindNative,
  captureNativeBindFailure,
  nativeReady,
  nativeSync,
  PlatformNativeError,
  settleCheckedHandleWork
} from "./win32.js";
